### ISSUE TITLE
game character 

### ISSUE THREAD

**Issue by ahmedaabbas** [ahmedaabbas/SpectoCMD#11]
as a game developer i want to see the example character and be able to control him

**Comment by ramy14** [comment]
controlling what !

**Comment by ramy14** [comment]
There's The Example character which  You can control fully using keyboard .. you can jump .. It's  basic function is to collect the random objects in the environment to get higher score .. then you will reach your target by collecting all the cubes in the field .. it will face some challenges through the commands from API ..

**Comment by zyadelashwal** [comment]
good job
